version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

hooks:
  ApplicationStart:
    - location: /home/ubuntu/build/scripts/deploy.sh
      timeout: 100
      runas: ubuntu
permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu
