# mysql
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://database-2.c83odifrrurw.ap-northeast-2.rds.amazonaws.com:3306/study_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration