# mysql
spring:
  datasource:
    url: jdbc:mysql://database-2.c83odifrrurw.ap-northeast-2.rds.amazonaws.com:3306/study_db
    username: admin
    password: 1234qwer!!
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect