jobs:
  backend_build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Zip the build files
        run: zip -r build.zip build/libs/*.jar

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload server files to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://weather.tj/deploy/

      - name: Deploy with AWS CodeDeploy (or other deployment services)
        run: # Deployment command here


      - name: Deploy with AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name tj-code-deploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name GROUP \
          --s3-location bucket=weather.tj,bundleType=zip,key=deploy/hous.zip

